version: '3'
services:
  database-mongo:
    container_name: vide-users-db
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - hackathon

volumes:
  mongo_data: {}

networks:
  hackathon:
    driver: bridge
